# docker compose up --build
services:
  node:
    container_name: nous
    restart: unless-stopped
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      # - .:/nous
      # Provides your Google Cloud application default credentials
      - ~/.config/gcloud:/home/nous/.config/gcloud
#    environment:
#      - var=value

