# docker compose up --build
services:
  node:
    container_name: nous-dev
    restart: always
    ports:
      - 4200:4200
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ~/.config/gcloud:/home/nous/.config/gcloud # Comment out if not using Google Cloud
      - .:/home/nous
      # Install node_modules into the container for cross-platform compatability
      - /home/nous/node_modules
      - /home/nous/frontend/node_modules
#    environment:
#      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
#      - var=value

