site_name: nous.ai
site_url: https://nous-docs.trafficguard.ai/
theme:
  name: material
  palette:
    primary: black

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - index.md
  - setup.md
  - functions.md
  - observability.md
  - xml-agent.md
  - software-engineer.md
  - code-review.md
  - integrations.md

plugins:
  - glightbox
