site_name: nous.ai
site_url: https://nous.trafficguard.ai/
theme:
  name: material
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/trafficguard/nous
repo_name: trafficguard/nous

nav:
  - index.md
  - setup.md
  - observability.md
  - functions.md
  - agents.md
  - autonomous-agents.md
  - software-engineer.md
  - code-review.md
  - integrations.md
  - roadmap.md
  - Blog:
      - blog/index.md

plugins:
  - glightbox
  - search
  - blog